### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by nuntawat007** [BusX/BusX-Carrier#102]

**Comment by nuntawat007** [comment]
- [x] Pricing passenger type route
- [x] Pricing passenger type stop pair
- [x] Segmented

**Comment by nuntawat007** [comment]
24-03-2560
- update delete button on trip like a reservation page

**Comment by winzaa123** [comment]
07/04/60
edit formvalidation pricepoint

**Comment by kamchaichopuk** [comment]
code service segmented

**Comment by kridsadaMun** [comment]
1. Pricings
    - [x] Pricing Index
    - [x] Pricing Add
    - [x] Pricing Edit [processing]
    - [x] Set Pricing All
2. Pricing Rules
    - [x] Pricing Rule Index
    - [x] Pricing Rule Add
    - [x] Pricing Rule Edit
