### ISSUE TITLE
Reservations

### ISSUE THREAD

**Issue by kamchaichopuk** [BusX/BusX-Carrier#13]
- [x] Reservation

**Comment by psukmak** [comment]
redesign summery of payment

**Comment by winzaa123** [comment]
> 20/3/60
- edit menu dashboard main for android,windows phone
- edit CSS dashboard index.php for IE 10+, Microsoft Edge
- edit customer detail CSS for Microsoft edge have problem

**Comment by winzaa123** [comment]
> 24/3/60

- edit dropdown input group

**Comment by winzaa123** [comment]
- [ ] edit  modal add addtional service
