### ISSUE TITLE
passenger

### ISSUE THREAD

**Issue by IFOOSOSAD** [BusX/BusX-Carrier#141]
-search passenger
-create/ update passenger 
-create/ update assign seat passenger
-cancel booking

**Comment by IFOOSOSAD** [comment]
-open booking

**Comment by Wannisa-Khiaokaeo** [comment]
-detail booking

**Comment by IFOOSOSAD** [comment]
-no show

**Comment by IFOOSOSAD** [comment]
-refund

**Comment by IFOOSOSAD** [comment]
-rebooking

**Comment by kridsadaMun** [comment]
1. Rebooking
   - [x] Fix bug modal transition
   - [x] Check case for use with Reservation page
   - [x] Calculate price [**_Wait new service_**]
   - [ ] Calculate discount [**_Wait new service_**]
   - [x] Calculate tax [**_Wait new service_**]
   - [x] Calculate total [**_Wait new service_**]

2. Open
   - [x] Fix bug modal transition
   - [x] Check case for use with Reservation page
   - [ ] Calculate price [**_Wait new service_**]
   - [ ] Calculate discount [**_Wait new service_**]
   - [ ] Calculate tax [**_Wait new service_**]
   - [ ] Calculate total [**_Wait new service_**]

3. Refund
   - [x] Fix bug modal transition
   - [x] Check case for use with Reservation page
   - [x] Calculate price [**_Wait new service_**]
   - [x] Calculate discount [**_Wait new service_**]
   - [x] Calculate tax [**_Wait new service_**]
   - [x] Calculate total [**_Wait new service_**]
