### ISSUE TITLE
Update bootstrap 4 beta

### ISSUE THREAD

**Issue by psukmak** [BusX/BusX-Carrier#142]
use new boostrap 4 beta style

**Comment by psukmak** [comment]
- Fee
- User Group
- User 
- My Account
- Account Setting
- Fare Restriction
-Expense 
-Accessory
-Memo
-Tax
-Commission
-Agent

-Payment Channels
-Amenity Group
-Seat Item
-Sales Item
-Additional Service
-Employee

**Comment by nuntawat007** [comment]
Test & Fixed UI-Programming
- Expense
- Accessory
- Memo
- Tax
- Commission
- Agent
- Carrier
- Payment Channels
- Amenity Group
- Seat Item
- Sales Item
- Additional Service
- Employee
- Fee
- User Group
- User
- My Account
- Account Setting
- Fare Restriction
- Stop
- Vehicle
- Cabin Class
- Seat Maps

**Comment by kridsadaMun** [comment]
- system setting
- pricing
- discounts
- fare restriction
- fare type
- promotion code
