### ISSUE TITLE
Fare Restrictions

### ISSUE THREAD

**Issue by kamchaichopuk** [BusX/BusX-Carrier#36]

**Comment by chan-opensource** [comment]
- [Index]

- [Add&Edit ]

**Comment by chan-opensource** [comment]
แก้คำเพิ่มเติมหน้า ADD

**Comment by chan-opensource** [comment]
แก้ Must be before: [Input] hrs before departure time.

**Comment by chan-opensource** [comment]
ลดช่องว่างระหว่าง  [Input] hrs before departure time.

**Comment by winzaa123** [comment]
16/2/60
- edit form add/edit

**Comment by winzaa123** [comment]
17/2/60
- check jquery
