### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by kamchaichopuk** [BusX/BusX-Carrier#41]
- [x] Index
- [x] Add pricing
  - [x] menu-responsive
  - [x] select route,vehicle
  - [x] search stop
  - [x] search trip
  - [x] add date transaction date, service day
  - [x] add service day
  - [x] form in mobile
  - [x] add pricing in segmented model
- [x] Setprice
  - [x] borkorsor
  - [x] markup_markdown
  - [x] route
  - [x] Segmented

**Comment by winzaa123** [comment]
หัวข้อตรวจสอบ
 -  select หัวข้อ route, vehicle class ใน Pricing Rules
 -  ปุ่ม on/off แต่ละ Pricing
 -  Process การ Add stop pair

**Comment by winzaa123** [comment]
2/2/60 (P'nong,win)
edit form add update to bootstrap 4.0.6

**Comment by winzaa123** [comment]
3/2/60
edit jquery in UI Programming

**Comment by nuntawat007** [comment]
22/03/60
- add pricing passenger type route / pricing passenger type stop pair page

**Comment by winzaa123** [comment]
21/03/60

- Design segmented in set price

**Comment by winzaa123** [comment]
> 23/03/60 - 24/03/60

- test segmented calendar
- edit css sidebar (delete trip pricing rules) { 24/3/60}

**Comment by winzaa123** [comment]
> 27/03/60 - 29/03/60
-  Edit segmented calendar
- increase badge inventory exceeded

> 30/03/60 - 31/03/60
- edit modal update inventory
- test calendar event CSS

**Comment by winzaa123** [comment]
> 07/04/60
- Edit Price point col
- edit formvalidation

**Comment by kridsadaMun** [comment]
- price setting
- pricing
- pricing add
- pricing edit
- pricing rule
- pricing rule add
- pricing rule edit

**Comment by kridsadaMun** [comment]
1. Pricings
    - [x] Pricing Index
    - [x] Pricing Add
    - [x] Pricing Edit
    - [ ] Set Pricing All [waitting pricing process]
2. Pricing Rules
    - [x] Pricing Rule Index
    - [x] Pricing Rule Add
    - [x] Pricing Rule Edit
