### ISSUE TITLE
pricing.service

### ISSUE THREAD

**Issue by nuntawat007** [BusX/BusX-Carrier#63]

**Comment by kamchaichopuk** [comment]
เหลือ pricing segmented อย่างเดียว

**Comment by nuntawat007** [comment]
add passenger type function
- [x] get_pm_passenger_type_route()
- [x] update_pm_passenger_type_route()
- [x] get_pm_passenger_type_stop_pair()
- [x] update_pm_passenger_type_stop_pair()


add segmented function
- [x] get_pm_segmented
- [x] get_pm_segmented_inventory
- [x] update_pm_segmented_price_point

**Comment by kamchaichopuk** [comment]
code service segmented

**Comment by kamchaichopuk** [comment]
-edit service pricing
-create service fare_type
-waiting for the test

**Comment by kamchaichopuk** [comment]
delete field cabin_class in service pricing
