### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by winzaa123** [BusX/BusX-Carrier#80]
- [x] User index
   - [x] Add
   - [x] Edit
   - [x] delete
   - [x] Edit password
   - [x] Edit ticket form
   - [x] My account  edit information
   - [x] My account  change password
   - [x] My account  settings (ticket form)
   - [x] My password
- [x] User group index
   - [x] Add (Basic)
   - [x] Edit (Basic)
   - [x] delete
   - [ ]  Privileges

**Comment by winzaa123** [comment]
22/12/59
 - function delete image 24 hr.

**Comment by winzaa123** [comment]
11/1/60
avatar.js  alert first-child

**Comment by kamchaichopuk** [comment]
waiting edit process single sign-on

**Comment by kridsadaMun** [comment]
- Modal Search for assign user
- Assign user
