### ISSUE TITLE
System Settings

### ISSUE THREAD

**Issue by winzaa123** [BusX/BusX-Carrier#81]
- [x] index
   - [x]   currency
   - [x]  ticket form 
      - [x]  ticket index 
      - [x]  ticket footer message
          - [x]  add
          - [x]  edit
      - [x]  ticket form settings
          - [x]  upload image

**Comment by winzaa123** [comment]
CSS sidebar 23/12/2559
-sidebar submenu

**Comment by Wannisa-Khiaokaeo** [comment]
vehicle type - add vehicle type

**Comment by kridsadaMun** [comment]
1. Device Authorize
2. Themes
3. Food Coupon Setting
4. Food Coupon Rules
       - Food coupon rule index
       - Food coupon rule add
       - Food coupon rule edit
