### ISSUE TITLE
Trips

### ISSUE THREAD

**Issue by nuntawat007** [BusX/BusX-Carrier#82]
Waiting get_seat_block service data

**Comment by nuntawat007** [comment]
Waiting new trip_service [create, update]

**Comment by nuntawat007** [comment]
Waiting image seatmap

**Comment by nuntawat007** [comment]
- [x] Waiting new trip_service [create, update]
- [x] Waiting image seatmap

**Comment by winzaa123** [comment]
9/2/60
increase trip edit stop 
*wait test input data (time duration) Jquery

**Comment by winzaa123** [comment]
10/2/60
increase jquery check time HH:MM
- [x] test trip edit stop

**Comment by nuntawat007** [comment]
- [x] add amenity group
